import 'package:elementals/models/elements.dart';
import 'package:elementals/bussiness_logic/core/element_list_manipulation.dart';

/// Object of blank element for arranging elements in [PeriodicTableListHandler].
final Elements nullElement = Elements(
    name: '',
    appearance: '',
    atomicMass: '',
    boil: '',
    category: '',
    density: '',
    discoveredBy: '',
    melt: '',
    molarHeat: '',
    namedBy: '',
    number: '',
    period: 0,
    group: 0,
    phase: '',
    source: '',
    bohrModelImage: '',
    bohrModel_3d: '',
    spectralImg: '',
    summary: '',
    symbol: '',
    xpos: 0,
    ypos: 0,
    wxpos: 0,
    wypos: 0,
    shells: [],
    electronConfiguration: '',
    electronConfigurationSemantic: '',
    electronAffinity: '',
    electronegativityPauling: '',
    ionizationEnergies: [],
    cpkHex: '',
    image: nullImageModel,
    block: '');

final ImageModel nullImageModel =
    ImageModel(title: '', url: '', attribution: '');

/// Object of Lanthanoids Label for arranging elements in [PeriodicTableListHandler].
final Elements lanthanoids = Elements(
    name: 'Lanthanoids',
    appearance: '',
    atomicMass: '',
    boil: '',
    category: '',
    density: '',
    discoveredBy: '',
    melt: '',
    molarHeat: '',
    namedBy: '',
    number: '57-71',
    period: 0,
    group: 0,
    phase: '',
    source: '',
    bohrModelImage: '',
    bohrModel_3d: '',
    spectralImg: '',
    summary: '',
    symbol: '',
    xpos: 0,
    ypos: 0,
    wxpos: 0,
    wypos: 0,
    shells: [],
    electronConfiguration: '',
    electronConfigurationSemantic: '',
    electronAffinity: '',
    electronegativityPauling: '',
    ionizationEnergies: [],
    cpkHex: '',
    image: nullImageModel,
    block: '');

/// Object of Actinoids label for arranging elements in [PeriodicTableListHandler].
final Elements actinoids = Elements(
    name: 'Actinoids',
    appearance: '',
    atomicMass: '',
    boil: '',
    category: '',
    density: '',
    discoveredBy: '',
    melt: '',
    molarHeat: '',
    namedBy: '',
    number: '89-103',
    period: 0,
    group: 0,
    phase: '',
    source: '',
    bohrModelImage: '',
    bohrModel_3d: '',
    spectralImg: '',
    summary: '',
    symbol: '',
    xpos: 0,
    ypos: 0,
    wxpos: 0,
    wypos: 0,
    shells: [],
    electronConfiguration: '',
    electronConfigurationSemantic: '',
    electronAffinity: '',
    electronegativityPauling: '',
    ionizationEnergies: [],
    cpkHex: '',
    image: nullImageModel,
    block: '');
